// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBdHH3YOjeyqf28rqdjWSgkdSqsAeSrh8',
    appId: '1:471973147966:web:eb1234567890abcdef', // Placeholder
    messagingSenderId: '471973147966',
    projectId: 'appflutter-592bc',
    authDomain: 'appflutter-592bc.firebaseapp.com',
    databaseURL: 'https://appflutter-592bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appflutter-592bc.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBdHH3YOjeyqf28rqdjWSgkdSqsAeSrh8',
    appId: '1:471973147966:android:7695e87a0fc7406907e86f',
    messagingSenderId: '471973147966',
    projectId: 'appflutter-592bc',
    databaseURL: 'https://appflutter-592bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appflutter-592bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBdHH3YOjeyqf28rqdjWSgkdSqsAeSrh8',
    appId: '1:471973147966:ios:eb1234567890abcdef', // Placeholder
    messagingSenderId: '471973147966',
    projectId: 'appflutter-592bc',
    databaseURL: 'https://appflutter-592bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appflutter-592bc.firebasestorage.app',
    iosBundleId: 'com.healthcare.medify',
  );
}
